# .github/workflows/auto-merge-dependabot.yml
name: Auto-merge Dependabot PRs

on:
  pull_request:
    branches:
      - main # O la tua branch principale, es. "master"

permissions:
  contents: write # Richiesto per il merge
  pull-requests: write # Richiesto per interagire con le PR

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.state == 'open'
    steps:
      - name: Check for passing status checks
        uses: "actions/github-script@v7"
        id: checks
        with:
          script: |
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });

            const passing = checks.check_runs.every(
              (check) => check.status === 'completed' && check.conclusion === 'success'
            );

            core.setOutput('all_passing', passing);

      - name: Merge Dependabot PR
        if: steps.checks.outputs.all_passing == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Questo token è fornito automaticamente da GitHub
